name: Renovate
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Renovate

        uses: renovatebot/github-action@v32.241.11
=======
        uses: renovatebot/github-action@v40.3.2

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
